CREATE TABLE TBL_MEMBER(
	MEMBER_ID NUMBER,
	LOGIN_ID VARCHAR2(1000),
	PASSWORD VARCHAR2(1000),
	NAME VARCHAR2(1000),
	AGE NUMBER,
	CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_ID)
);

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER;

SELECT * FROM TBL_MEMBER tm ;

DROP TABLE TBL_MEMBER;

INSERT INTO TBL_MEMBER(MEMBER_ID, LOGIN_ID, PASSWORD, NAME, AGE)
VALUES(0, '', '', '', 0);


CREATE TABLE TBL_TODO(
	TODO_ID NUMBER,
	TITLE VARCHAR2(1000),
	WRITER VARCHAR2(1000),
	TODO_DATE DATE,
	FINISHED NUMBER,
	CONSTRAINT PK_TODO PRIMARY KEY(TODO_ID)
);

CREATE SEQUENCE SEQ_TODO;

INSERT INTO TBL_TODO(TODO_ID, TITLE, WRITER, TODO_DATE, FINISHED)
VALUES(SEQ_TODO.NEXTVAL, '빨래하기', '김송호', '2024-06-28', 0);

SELECT
	TODO_ID,
	TITLE,
	WRITER,
	TO_CHAR(TODO_DATE, 'YYYY-MM-DD') TODO_DATE,
	FINISHED
FROM
	TBL_TODO
ORDER BY
	TODO_DATE


SELECT
	TODO_ID,
	TITLE,
	WRITER,
	TO_CHAR(TODO_DATE, 'YYYY-MM-DD') TODO_DATE,
	FINISHED
FROM
	TBL_TODO
WHERE TODO_ID = 3;











