CREATE TABLE TBL_MEMBER(
	MEMBER_ID NUMBER,
	LOGIN_ID VARCHAR2(1000),
	PASSWORD VARCHAR2(1000),
	GENDER CHAR(1),
	CONSTRAINT PK_MEMBER PRIMARY KEY(MEMBER_ID)
);

DROP SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_MEMBER;

SELECT * FROM TBL_MEMBER tm ;
